import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faCalendar, 
  faCheckCircle, 
  faClock, 
  faDollarSign,
  faCalculator,
  faCar,
  faTools,
  faInfoCircle,
  faUserTie,
  faShieldAlt,
  faClipboardCheck,
  faHome,
  faCarCrash,
  faSearch,
  faGasPump,
  faStar,
  faStarHalfAlt,
  faCertificate,
  faMessage,
  faXmark,
  faBars,
  faPaperPlane,
  faCamera,
  faUser
} from '@fortawesome/free-solid-svg-icons';

// Add all icons to the library
library.add(
  faCalendar, 
  faCheckCircle, 
  faClock, 
  faDollarSign,
  faCalculator,
  faCar,
  faTools,
  faInfoCircle,
  faUserTie,
  faShieldAlt,
  faClipboardCheck,
  faHome,
  faCarCrash,
  faSearch,
  faGasPump,
  faStar,
  faStarHalfAlt,
  faCertificate,
  faMessage,
  faXmark,
  faBars,
  faPaperPlane,
  faCamera,
  faUser
);
